//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXPRESSO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExpressoEntities : DbContext
    {
        public ExpressoEntities()
            : base("name=ExpressoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<Drink> Drinks { get; set; }
        public virtual DbSet<GalerryFilter> GalerryFilters { get; set; }
        public virtual DbSet<Gallery> Galleries { get; set; }
        public virtual DbSet<Header> Headers { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<CallU> CallUS { get; set; }
        public virtual DbSet<ExpressoFooter> ExpressoFooters { get; set; }
        public virtual DbSet<Newsletter> Newsletters { get; set; }
        public virtual DbSet<WorkingHour> WorkingHours { get; set; }
    }
}
