//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXPRESSO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpressoFooter
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string facebook_link { get; set; }
        public string twitter_link { get; set; }
        public string instagram_link { get; set; }
        public string youtube_link { get; set; }
        public string linkedin_link { get; set; }
        public string pinterest_link { get; set; }
    }
}
