//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXPRESSO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingHour
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string day1 { get; set; }
        public string hour1 { get; set; }
        public string day2 { get; set; }
        public string hour2 { get; set; }
        public string day3 { get; set; }
        public string hour3 { get; set; }
    }
}
